LUSSIS/Controllers/SupervisorDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using LUSSIS.Repositories;
using LUSSIS.Models.WebDTO;
using System.IO;
using System.Text.RegularExpressions;
using System.Diagnostics;
using LUSSIS.Constants;
using static LUSSIS.Constants.POStatus;
using static LUSSIS.Constants.DisbursementStatus;

namespace LUSSIS.Controllers
{
    //Authors: May Zin Ko, Douglas Lee Kiat Hui
    [Authorize(Roles = "manager, supervisor")]
    public class SupervisorDashboardController : Controller
    {
        private readonly PORepository _poRepo = new PORepository();
        private readonly DisbursementRepository _disbursementRepo = new DisbursementRepository();
        private readonly StockAdjustmentRepository _stockAdjustmentRepo = new StockAdjustmentRepository();
        private readonly StationeryRepository _stationeryRepo = new StationeryRepository();
        private readonly EmployeeRepository _employeeRepo = new EmployeeRepository();
        private readonly SupplierRepository _supplierRepo = new SupplierRepository();
        private readonly CategoryRepository _categoryRepo = new CategoryRepository();
        private readonly DepartmentRepository _departmentRepo = new DepartmentRepository();

        public ActionResult Index()
        {
            ViewBag.Message = User.IsInRole(Role.Supervisor) ? Role.Supervisor : Role.Manager;
            var totalAddAdjustmentQty = _stockAdjustmentRepo.GetPendingAdjustmentByType("add", ViewBag.Message).Count;
            var totalSubtractAdjustmentQty =
                _stockAdjustmentRepo.GetPendingAdjustmentByType("subtract", ViewBag.Message).Count;
            var fromList = new List<string>
            {
                DateTime.Now.AddMonths(-3).ToString("dd/MM/yyyy"),
                DateTime.Now.AddMonths(-2).ToString("dd/MM/yyyy"),
                DateTime.Now.AddMonths(-1).ToString("dd/MM/yyyy")
            };
            var dash = new SupervisorDashboardDTO
            {
                PendingPOTotalAmount = _poRepo.GetPendingPOTotalAmount(),
                PendingPOCount = _poRepo.GetPendingApprovalPO().Count,
                POTotalAmount = _poRepo.GetPOTotalAmount(fromList),
                PendingStockAdjAddQty = totalAddAdjustmentQty,
                PendingStockAdjSubtractQty = totalSubtractAdjustmentQty,
                PendingStockAdjCount = _stockAdjustmentRepo.GetPendingAdjustmentList().Count,
                TotalDisbursementAmount = _disbursementRepo.GetDisbursementTotalAmount(fromList),
                GetPendingAdjustmentByRole = _stockAdjustmentRepo.GetPendingAdjustmentByRole(ViewBag.Message).Count
            };

            return View(dash);
        }

        public JsonResult GetPiechartJson(string list, string date, string e)
        {
            var pileName = _categoryRepo.GetAllCategoryName().ToList();
            var pileValue = _poRepo.GetPOByCategory();

            return Json(new {ListOne = pileName, ListTwo = pileValue}, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetStackJSon()
        {
            var depList = _departmentRepo.GetAllDepartmentCode();
            var catList = _categoryRepo.GetAllCategoryIds();
            var fromList = new List<string>();
            var toList = new List<string>();

            var datevalue = new List<string>();

            fromList.Add(DateTime.Now.AddMonths(-3).ToString("dd/MM/yyyy"));
            fromList.Add(DateTime.Now.AddMonths(-2).ToString("dd/MM/yyyy"));
            fromList.Add(DateTime.Now.AddMonths(-1).ToString("dd/MM/yyyy"));

            datevalue.Add(DateTime.Now.AddMonths(-3).ToString("MMM/yyyy"));
            datevalue.Add(DateTime.Now.AddMonths(-2).ToString("MMM/yyyy"));
            datevalue.Add(DateTime.Now.AddMonths(-1).ToString("MMM/yyyy"));

            var titlevalue = depList;

            var listOne = new List<ReportTransferDTO>();
            for (int j = 0; j < fromList.Count; j++)
            {
                Debug.WriteLine(j);
                var rto = new ReportTransferDTO {timeValue = datevalue[j]};
                var xvalue = new List<double>();
                foreach (var department in depList)
                {
                    var temp = _disbursementRepo.GetDisAmountByDep(department, catList, fromList[j]);
                    xvalue.Add(temp);
                }

                rto.xvalue = xvalue;
                listOne.Add(rto);
            }

            return Json(new {title = titlevalue, ListOne = listOne}, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "manager,supervisor")]
        public ActionResult TrendAnalysis()
        {
            ViewBag.Departments = _departmentRepo.GetAll().Where(x => x.DeptCode != "STNR");
            ViewBag.Categories = _categoryRepo.GetAll();
            ViewBag.Suppliers = _supplierRepo.GetAll();

            return View();
        }

        public ActionResult ReturnJsonData()
        {
            //get post results from ajax
            Request.InputStream.Position = 0;
            var input = new StreamReader(Request.InputStream).ReadToEnd();
            var filter = new AjaxInputFilter(input);

            //get Dictionary of category id and names
            Dictionary<string, string> categoryDic =
                _categoryRepo.GetAll().ToDictionary(x => x.CategoryId.ToString(), x => x.CategoryName);
            Dictionary<string, string> groupDic;
            groupDic = filter.IsDisburse
                ? _departmentRepo.GetAll().ToDictionary(x => x.DeptCode, x => x.DeptName)
                : _supplierRepo.GetAll().ToDictionary(x => x.SupplierId.ToString(), x => x.SupplierName);

            //get data
            IEnumerable<Detail> allList;
            if (filter.IsDisburse)
                allList = _disbursementRepo.GetAllDisbursementDetails().Where(x => x.Disbursement.Status != InProcess)
                    .Select(x => new Detail
                    {
                        Date = x.Disbursement.CollectionDate,
                        Qty = x.ActualQty,
                        Cost = x.UnitPrice * x.ActualQty,
                        CategoryId = x.Stationery.CategoryId,
                        Group = x.Disbursement.DeptCode
                    }).Where(x => x.Date >= filter.FromDate && x.Date <= filter.ToDate);
            else
                allList = _poRepo.GetAllPurchaseOrderDetails().Where(x =>
                        x.PurchaseOrder.Status != Rejected && x.PurchaseOrder.Status != Pending)
                    .Select(x => new Detail
                    {
                        Date = x.PurchaseOrder.CreateDate,
                        Qty = x.ReceiveQty,
                        Cost = x.UnitPrice * x.ReceiveQty,
                        CategoryId = x.Stationery.CategoryId,
                        Group = x.PurchaseOrder.SupplierId.ToString()
                    }).Where(x => x.Date >= filter.FromDate && x.Date <= filter.ToDate);
            var allList1 = allList;
            var allListTotal = allList;

            int noOfMonths = (filter.ToDate.Year - filter.FromDate.Year) * 12 + filter.ToDate.Month -
                             filter.FromDate.Month + 1;
            string[] categories = filter.Categories.Split(',');
            if (filter.Categories == "")
                categories = categoryDic.Keys.ToArray();
            categories = allList.Select(x => x.CategoryId.ToString()).Distinct().Intersect(categories).ToArray();
            string[] groups = filter.Group.Split(',');
            if (filter.Group == "")
                groups = groupDic.Keys.ToArray();
            groups = allList.Select(x => x.Group).Distinct().Intersect(groups).ToArray();

            //get label
            object[] arr = new object[noOfMonths + 1];
            object[] arr1 = new object[noOfMonths + 1];
            object[] arrTotal = new object[noOfMonths + 1];
            string[] monthLabel = new string[groups.Length + 1];
            monthLabel[0] = "Month";
            for (int i = 0; i < groups.Length; i++)
                monthLabel[i + 1] = groupDic[groups[i]];
            arr[0] = monthLabel;
            string[] monthLabel1 = new string[categories.Length + 1];
            monthLabel1[0] = "Month";
            for (int i = 0; i < categories.Length; i++)
                monthLabel1[i + 1] = categoryDic[categories[i]];
            arr1[0] = monthLabel1;
            string[] monthLabelTotal = new string[2];
            monthLabelTotal[0] = "Month";
            monthLabelTotal[1] = filter.IsQty ? "Qty" : "Cost";
            arrTotal[0] = monthLabelTotal;

            allList = Detail.FilterByCategory(allList, categories).ToList();
            allList1 = Detail.FilterByGroup(allList, groups).ToList();
            for (int i = 0; i < noOfMonths; i++)
            {
                object[] rowArr = new object[groups.Length + 1];
                object[] rowArr1 = new object[categories.Length + 1];
                object[] rowArrTotal = new object[2];
                rowArr[0] = filter.FromDate.AddMonths(i).ToString("yyyyMM");
                rowArr1[0] = filter.FromDate.AddMonths(i).ToString("yyyyMM");
                rowArrTotal[0] = filter.FromDate.AddMonths(i).ToString("yyyyMM");
                for (int j = 0; j < groups.Length; j++)
                {
                    rowArr[j + 1] = Detail.FilterByYyymm(allList, rowArr[0] as string)
                        .Where(x => x.Group == groups[j]).Sum(x => filter.IsQty ? x.Qty : x.Cost);
                }

                for (int j = 0; j < categories.Length; j++)
                {
                    rowArr1[j + 1] = Detail.FilterByYyymm(allList1, rowArr1[0] as string)
                        .Where(x => x.CategoryId.ToString() == categories[j]).Sum(x => filter.IsQty ? x.Qty : x.Cost);
                }

                rowArrTotal[1] =
                    Detail.FilterByYyymm(
                            Detail.FilterByCategory(

LUSSIS/Views/SupervisorDashboard/Index.cshtml
@using LUSSIS.Constants
@model LUSSIS.Models.WebDTO.SupervisorDashboardDTO
@{
    ViewBag.Title = "Dashboard";
}
<h2>My Dashboard</h2>
<hr/>

<div class="row">
    <div class="col-lg-3 col-md-6 text-center">
        <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 50rem; min-height: 22rem">
            <h5 class="card-header mt-0">Pending Adjustments</h5>
            <div class="card-body">
                @if (@Model.PendingStockAdjCount == 0)
                {
                    <div class="alert alert-dismissible alert-info p-4">
                        <h6>No pending stock adjustment at the moment.</h6>
                    </div>
                }
                else
                {
                    <table class="table mt-3">
                        <tr>
                            <th>
                                <small>No. of requests&nbsp;&nbsp;&nbsp;</small>
                                @Model.GetPendingAdjustmentByRole
                            </th>
                        </tr>

                        <tr>
                            <td>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <h3 class="mt-2 mb-0 text-muted">
                                            +
                                            @if (Model.GetPendingAdjustmentByRole == 0)
                                            {
                                                <text>0</text>
                                            }
                                            else
                                            {
                                                @Model.PendingStockAdjAddQty
                                            }
                                        </h3>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <h3 class="mt-2 mb-0 text-muted">
                                            -
                                            @if (Model.GetPendingAdjustmentByRole == 0)
                                            {
                                                <text>0</text>
                                            }
                                            else
                                            {
                                                @Model.PendingStockAdjSubtractQty
                                            }
                                        </h3>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </table>
                }
            </div>
            <div class="card-footer text-center">
                @Html.ActionLink("View All", "ViewPendingStockAdj", "StockAdjustment", null, new {@class = "btn btn-info", style = "width:100%"})
            </div>
        </div>
    </div>

    @if (User.IsInRole(Role.Supervisor))
    {
        <div class="col-lg-3 col-md-6 text-center">
            <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 50rem; min-height: 22rem">
                <h5 class="card-header mt-0">Pending P.O. </h5>
                <div class="card-body">
                    @if (@Model.PendingPOCount == 0)
                    {
                        <div class="alert alert-dismissible alert-info p-4">
                            <h6>No pending purchase order at the moment.</h6>
                        </div>
                    }
                    else
                    {
                        <table class="table mt-3">
                            <tr>
                                <th>
                                    <small>No. of requests&nbsp;&nbsp;&nbsp;</small> @Model.PendingPOCount</th>
                            </tr>

                            <tr>
                                <td>

                                    <h3 class="mt-2 mb-0 text-muted">$ @Model.PendingPOTotalAmount.ToString("0.00")</h3>


                                </td>

                            </tr>

                        </table>
                    }

                </div>
                <div class="card-footer text-center">
                    @Html.ActionLink("View All", "PendingPO", "PurchaseOrders", null, new {@class = "btn btn-info", style = "width:100%"})
                </div>
            </div>
        </div>
    }
    <div class="col-lg-3 col-md-6 text-center">
        <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 50rem; min-height: 22rem">
            <h5 class="card-header mt-0">Total PO Expenditure</h5>
            <div class="card-body">

                <table class="table mt-3">
                    <tr>
                        <th>
                            <small>For past three months</small>
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <h3 class="mt-2 mb-0 text-muted">
                                $ @Model.POTotalAmount.ToString("#.00")
                            </h3>

                        </td>
                    </tr>
                </table>


            </div>
            <div class="card-footer text-center">
                @Html.ActionLink("Purchase Trend", "TrendAnalysis", "SupervisorDashboard", null, new {@class = "btn btn-warning", style = "width:100%"})
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-6 text-center">
        <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 50rem; min-height: 22rem">
            <h5 class="card-header mt-0">Total Chargeback</h5>
            <div class="card-body">


                <table class="table mt-3">
                    <tr>
                        <th>
                            <small>For past three months</small>
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <h3 class="mt-2 mb-0 text-muted">
                                $@Model.TotalDisbursementAmount.ToString("#.00")
                            </h3>

                        </td>
                    </tr>
                </table>


            </div>
            <div class="card-footer text-center">
                @Html.ActionLink("Demand Trend", "TrendAnalysis", "SupervisorDashboard", null, new {@class = "btn btn-success", style = "width:100%"})
            </div>
        </div>
    </div>
</div>

<hr/>
<br/>
<div class="row">
    <div class="col-lg-6 text-center">
        <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 100rem; min-height: 20rem">
            <h5 class="card-header mt-0">Stationery Expenditure for Past Three Months</h5>
            <div class="card-body">
                <div id="chart_div" style="max-width: 100rem; min-height: 50rem"></div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 text-center">
        <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 100rem; min-height: 50rem">
            <h5 class="card-header mt-0">Chargeback Per Department for Past Three Months</h5>
            <div class="card-body">
                <div id="stack_div" style="max-width: 100rem; min-height: 50rem"></div>
            </div>
        </div>
    </div>
</div>

@section scripts
{

    @Scripts.Render("https://www.gstatic.com/charts/loader.js")

    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['corechart'] });

        //Call function after Google Chart is loaded, it is required, otherwise you may get error
        google.charts.setOnLoadCallback(DrawPieChartLoad);

        google.charts.setOnLoadCallback(DrawStackChartLoad);


        function DrawPieChartLoad() {
            $(function() {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Content("~/")SupervisorDashboard/GetPiechartJson?list=aaa&date=bbbb&&e=cdefe',
                    success: function(chartsdata) {

                        var first = chartsdata.ListOne;
                        var second = chartsdata.ListTwo;

                        var data = new google.visualization.DataTable();

                        data.addColumn('string', 'CategoryName');
                        data.addColumn('number', 'PostCount');

                        //Loop through each list data

                        for (var i = 0; i < first.length; i++) {
                            if (second[i] !== 0) {
                                data.addRow([first[i], second[i]]);
                            }

                        }

                        // Instantiate and draw our chart, passing in some options
                        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));

                        //Draw pie chart command with data and chart options
                        chart.draw(data,
                            {
                                @*  title: "Stationery Expenditure for Past three months",*@
                                //position: "top",
                                fontsize: "30px",
                                width: "100%",
                                height: "100%",
                                fontName:
                                    "Ubuntu, -apple - system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, sansserif",
                                colors: [
                                    '#8dd3c7', '#ffffb3', '#bebada', '#fb8072', '#80b1d3', '#fdb462', '#b3de69',
                                    '#fccde5', '#d9d9d9', '#bc80bd', '#ccebc5', '#ffed6f', '#a6cee3', '#1f78b4',
                                    '#73bfe5', '#88d6f8', '#b2df8a', '#33a02c', '#fb9a99', '#e31a1c', '#fdbf6f',
                                    '#ff7f00', '#cab2d6', '#6a3d9a', '#ffff99', '#b15928', '#d1ae2b', '#b38849',
                                    '#d8a35c', '#636466', '#a09f9f', '#31536e', '#4c7ea4', '#73bfe5', '#88d6f8'
                                ],
                                backgroundColor: "#f2fcf5",
                                legend: { position: "bottom" }
                            }
                        );

                    },
                    error: function() {
                        alert("Error loading data! Please try again.");
                    }
                });
            });

        }


        function DrawStackChartLoad() {
            $(function() {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Content("~/")SupervisorDashboard/GetStackJson',
                    success: function(chartsdata) {
                        var data = new google.visualization.DataTable();

                        var title = chartsdata.title;
                        var listone = chartsdata.ListOne;

                        for (var i = 0; i < title.length + 1; i++) {
                            if (i === 0) {
                                data.addColumn("string", 'Time');
                            } else {
                                data.addColumn('number', title[i - 1]);
                            }
                        }

                        data.addRows(listone.length);
                        for (var j = 0; j < listone.length; j++) {
                            var tmpTime = listone[j].timeValue;
                            var tmpXvalue = listone[j].xvalue;
                            for (var k = 0; k < title.length + 1; k++) {
                                if (k === 0) {
                                    data.setValue(j, k, tmpTime);
                                } else {
                                    data.setValue(j, k, tmpXvalue[k - 1]);
                                }
                            }
                        }


                        var options = {
                            Title: "Charge Back for each department for past three months",
                            width: "100%",
                            fontsize: "30px",
                            fontName:
                                "Ubuntu, -apple - system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, sansserif",
                            height: "100%",
                            legend: { position: 'top', maxLines: 3 },
                            bar: { groupWidth: '75%' },
                            isStacked: true,
                            colors: [
                                '#a6cee3', '#1f78b4', '#b2df8a', '#33a02c', '#fb9a99', '#e31a1c', '#fdbf6f', '#ff7f00',
                                '#cab2d6'
                            ],
                            backgroundColor: "#f2fcf5"
                        };

                        // Instantiate and draw the chart.
                        var chart = new google.visualization.BarChart(document.getElementById('stack_div'));
                        chart.draw(data, options);

                    },
                    error: function() {
                        alert("Error loading data! Please try again.");
                    }
                });
            });

        }
    </script>
}

@*Authors: May Zin Ko*@

LUSSIS/Views/SupervisorDashboard/SupervisorDashboard.cshtml
@model LUSSIS.Models.WebDTO.SupervisorDashboardDTO

<script>


    window.onload = function () {
        var role = @Html.Raw(Json.Encode(ViewBag.Message));
         if (role=="supervisor") {
          
            document.getElementById("notShowManager").style.display = "block";

        }
         else {
             
            document.getElementById("notShowManager").style.display = "none";
        }

    }

</script>

@Scripts.Render("https://www.gstatic.com/charts/loader.js")

<script type="text/javascript">
    google.charts.load('current', { 'packages': ['corechart'] });

    //Call function after Google Chart is loaded, it is required, otherwise you may get error
    google.charts.setOnLoadCallback(DrawPieChartLoad);

    google.charts.setOnLoadCallback(DrawBarChartLoad);

    function DrawPieChartLoad() {
        $(function () {
            $.ajax({
                type: 'GET',
                url: '/SupervisorDashboard/GetPiechartJSON',
                success: function (chartsdata) {
                    // Callback that creates and populates a data table,
                    // instantiates the pie chart, passes in the data and
                    // draws it

                    //get JSONList from Object


                    // alert(result.FirstList[x].Name);
                    //alert(result.SecondList[x].Name);

                    var first = chartsdata.ListOne;
                    var second = chartsdata.ListTwo;

                    var data = new google.visualization.DataTable();

                    data.addColumn('string', 'CategoryName');
                    data.addColumn('number', 'PostCount');

                    //Loop through each list data

                    for (var i = 0; i < first.length; i++) {
                        if (second[i] != 0) {
                            data.addRow([first[i], second[i]]);
                        }

                    }

                    // Instantiate and draw our chart, passing in some options
                    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));

                    //Draw pie chart command with data and chart options
                    chart.draw(data,
                        {
                            title: "Stationery Trend Analysis",
                            position: "top",
                            fontsize: "25px",
                            width: "600",
                            height: "600",
                        });

                },
                error: function () {
                    alert("Error loading data! Please try again.");
                }
            });
        })

    }

    /////this one is for department
    function DrawBarChartLoad() {
        $(function () {
            $.ajax({
                type: 'GET',
                url: '/SupervisorDashboard/GetBarchartJSON',
                success: function (chartsdata) {
                    var first = chartsdata.firstList;
                    var second = chartsdata.secondList;

                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Department');
                    data.addColumn('number', 'Amount');

                    //Loop through each list data

                    for (var i = 0; i < first.length; i++) {
                        if (second[i] != 0) {
                            data.addRow([first[i], second[i]]);
                        }
                    }
                    var chart = new google.visualization.BarChart(document.getElementById('bar_div'));


                    chart.draw(data,
                        {
                            title: "Department Trend Analysis",
                            position: "top",
                            fontsize: "25px",
                            width: "400",
                            height: "600",
                        });
                },
                error: function () {
                    alert("Error loading data! Please try again.");
                }
            });
        })

    }


</script>
<div id="a"></div>
<h2>Dashboard for @ViewBag.Message</h2>
<div class="row">
    <div class="class=" col-4">
        <div class="bs-component">
            <div class="card bg-light mb-3" style="max-height: 10rem; min-width: 15rem; margin-right: 1rem">
                <div class="col-xs-12 text-center">
                    <div class="card bg-info text-white">
                        <div class="card-header">Pending Adjustment <span style="padding-left:3em">@Model.PendingStockAdjCount</span> </div>
                        <div class="card-body"><span style="padding-left:2em">+ @Model.PendingStockAdjAddQty</span><span style="padding-left:3em">- @Model.PendingStockAdjSubtractQty</span> </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="class="col-3" id="notShowManager" style="display:none;">
        <div class="bs-component">
            <div class="card bg-light mb-3" style="max-height: 10rem; min-width: 15rem; margin-right: 1rem">
                <div class="col-xs-12 text-center">

                    <div class="card bg-info text-white">
                        <div class="card-header">Pending Purchase Order <span style="padding-left:3em">@Model.PendingPOCount</span></div>
                        <div class="card-body"><span style="padding-left:5em">$@Model.PendingPOTotalAmount.ToString("#.00")</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="class=" col-lg-8">
        <div class="bs-component">
            <div class="card bg-light mb-3" style="max-height: 10rem; min-width: 15rem; margin-right: 1rem">
                <div class="col-xs-12 text-center">

                    <div class="card bg-info text-white">
                        <div class="card-header">Total ChargeBack</div>
                        <div class="card-body"><span style="padding-left:5em">$@Model.TotalDisbursementAmount.ToString("#.00")</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="class=" col-lg-8">
        <div class="bs-component">
            <div class="card bg-light mb-3" style="max-height: 10rem; min-width: 15rem; margin-right: 1rem">
                <div class="col-xs-12 text-center">

                    <div class="card bg-info text-white">
                        <div class="card-header">Total PO Expenditure</div>
                        <div class="card-body"><span style="padding-left:5em">$@Model.PendingPOTotalAmount.ToString("#.00")</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="row">
    @*<img src="@Url.Action("CharterColumn")" alt="chart" />*@

</div>
<div class="row">
    @**<img src="@Url.Action("PieChartColumn")" alt="chart" />*@

</div>
<div class="row">
    <div class="col-md-6">
        <div id="chart_div"></div>
    </div>
    <div class="col-md-6">
        <div id="bar_div"></div>
    </div>
</div>