LUSSIS/Controllers/RequisitionController.cs
using LUSSIS.Models;
using LUSSIS.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using LUSSIS.Exceptions;
using LUSSIS.Models.WebDTO;
using PagedList;

namespace LUSSIS.Controllers
{
    public class RequisitionController : Controller
    {
       
        private RequisitionRepository reqRepo = new RequisitionRepository();
        private EmployeeRepository empRepo = new EmployeeRepository();
        private StationeryRepository statRepo = new StationeryRepository();

        //TODO: Add authroization - DepartmentHead or Delegate only
        // GET: Requisition
        public ActionResult Pending()
        {
            return View(reqRepo.GetRequisitionsByStatus("pending"));
        }

        //TODO: Add authroization - DepartmentHead or Delegate only
        [HttpGet]
        public async Task<ActionResult> Detail(int reqId)
        {
            var req = await reqRepo.GetByIdAsync(reqId);
            if (req != null)
            {
                return View(req);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest); ;
        }

        //TODO: Add authroization - DepartmentHead or Delegate only
        [HttpPost]
        public async Task<ActionResult> Detail([Bind(Include = "RequisitionId,RequisitionEmpNum,RequisitionDate,RequestRemarks,ApprovalRemarks")] Requisition requisition, string SubmitButton)
        {
            if (ModelState.IsValid)
            {

                requisition.ApprovalEmpNum = empRepo.GetCurrentUser().EmpNum;
                requisition.ApprovalDate = DateTime.Today;
                if (SubmitButton == "Approve")
                {
                    requisition.Status = "approved";
                    await reqRepo.UpdateAsync(requisition);
                    return RedirectToAction("index");
                }

                if (SubmitButton == "Reject")
                {
                    requisition.Status = "reject";
                    await reqRepo.UpdateAsync(requisition);
                    return RedirectToAction("index");
                }
            }
            return RedirectToAction("index");
        }

        //TODO: View requisition details (without approve and reject button)
        // [employee page] GET: Requisition/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //TODO: return create page, only showing necessary fields
        // GET: Requisition/Create
        public ActionResult Create()
        {
            return View();
        }

        // TODO: 1. create new requisition, 2. it's status set to pending, 3. send notification to departmenthead
        // [employee page] POST: Requisition/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // TODO: only implement once main project is done. Enable editing if status is pending
        // [employee page]  GET: Requisition/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // TODO: only enable editing if status is pending
        // [employee page]  POST: Requisition/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
               return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Requisition/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Requisition/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        private RequisitionRepository reqrepo = new RequisitionRepository();
        private StationeryRepository strepo = new StationeryRepository();
        private EmployeeRepository erepo = new EmployeeRepository();
        // GET: DeptEmpReqs
        
        public ActionResult Index(string searchString, string currentFilter, int? page)
        {
            List<Stationery> stationerys = strepo.GetAll().ToList<Stationery>();
            if (searchString != null)
            { page = 1; }
            else
            {
                searchString = currentFilter;
            }
            if (!String.IsNullOrEmpty(searchString))
            { stationerys = strepo.GetByDescription(searchString).ToList(); }
            else { stationerys = strepo.GetAll().ToList(); }
            int pageSize = 15;
            int pageNumber = (page ?? 1);
            return View(stationerys.ToPagedList(pageNumber, pageSize));
        }

        // /Requisition/AddToCart
        [HttpPost]
        public ActionResult AddToCart(string id, int qty)
        {
            Cart cart = new Cart(strepo.GetById(id), qty);
            (Session["MyCart"] as ShoppingCart).addToCart(cart);
            return RedirectToAction("Index");
            //return Json("ok");

        }
        //GET: MyRequisitions
        //public async Task<ActionResult> EmpReq(int EmpNum)
        //{
        //    return View(reqRepo.GetRequisitionByEmpNum(EmpNum));
        //}
        public ActionResult EmpReq(string currentFilter, int? page)
        {           
            int id=erepo.GetCurrentUser().EmpNum;
            List<Requisition> reqlist = reqrepo.GetRequisitionByEmpNum(id).OrderByDescending(s=>s.RequisitionDate).ToList();
            int pageSize = 15;
            int pageNumber = (page ?? 1);
            return View(reqlist.ToPagedList(pageNumber,pageSize));
        }
        // GET: Requisitions/EmpReqDetail/5
        [HttpGet]
        public ActionResult EmpReqDetail(int id)
        {
            List<RequisitionDetail> requisitionDetail = reqRepo.GetRequisitionDetail(id).ToList<RequisitionDetail>();
            return View(requisitionDetail);
        }
        [HttpPost]
        public ActionResult SubmitReq()
        {
            var itemNum = (List<string> )Session["itemNub"];
            var itemQty = (List<int>)Session["itemQty"];
            int reqEmp = erepo.GetCurrentUser().EmpNum;
            DateTime reqDate = System.DateTime.Now.Date;
            string status = "pending";
            string remarks = Request["remarks"];
            if (itemNum != null)
            {
                Requisition requisition = new Requisition();
                requisition.RequestRemarks = remarks;
                requisition.RequisitionDate = reqDate;
                requisition.RequisitionEmpNum = reqEmp;
                requisition.Status = status;
                reqrepo.Add(requisition);
                for (int i = 0; i < itemNum.Count; i++)
                {
                    RequisitionDetail requisitionDetail = new RequisitionDetail();
                    requisitionDetail.RequisitionId = requisition.RequisitionId;
                    requisitionDetail.ItemNum = itemNum[i];
                    requisitionDetail.Quantity = itemQty[i];
                    reqrepo.AddRequisitionDetail(requisitionDetail);
                }
                Session["itemNub"] = null;
                Session["itemQty"] = null;
                Session["MyCart"] = new ShoppingCart();
                //return View();
                return RedirectToAction("EmpReq");
            }
            else
            {
                Response.Write("<script>alert('Your cart is empty')</script>");
                return RedirectToAction("EmpCart");
            }
        }
        public ActionResult EmpCart()
        {
            ShoppingCart mycart = (ShoppingCart)Session["MyCart"];
            return View(mycart.GetAllCartItem());
        }
        [HttpPost]
        public ActionResult DeleteCartItem(string id, int qty)
        {

            ShoppingCart mycart = Session["MyCart"] as ShoppingCart;
            mycart.deleteCart(id);
            return RedirectToAction("EmpCart");
        }
        //Stock Clerk's page
        public ActionResult Consolidated()
        {

            return View(new RetrievalItemsWithDateDTO{retrievalItems = reqRepo.GetConsolidatedRequisition().ToList(), collectionDate = DateTime.Today});
        }

        //TODO: Add authorization - Stock Clerk only 
        //click on generate button - post with date selected
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Retrieve([Bind(Include = "collectionDate")] RetrievalItemsWithDateDTO listWithDate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    return View(reqRepo.ArrangeRetrievalAndDisbursement(listWithDate.collectionDate));
                }

                throw new InvalidDateException();
            }
            catch (InvalidDateException /* dex */)
            {

            }

            return View("Retrieve");
        }

        [HttpGet]
        public ActionResult ApproveReq(int Id, String Status)
        {
            ReqApproveRejectDTO reqDTO = new ReqApproveRejectDTO();
            reqDTO.RequisitionId = Id;
            reqDTO.Status = Status;
            return PartialView("ApproveReq", reqDTO);
        }

        [HttpPost]
        public ActionResult ApproveReq([Bind(Include = "RequisitionId,ApprovalRemarks,Status")]ReqApproveRejectDTO RADTO)
        {
            if (ModelState.IsValid)
            {
                Requisition req = reqRepo.GetById(RADTO.RequisitionId);

LUSSIS/Controllers/WebAPI/RequisitionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Http;
using LUSSIS.Constants;
using LUSSIS.Emails;
using LUSSIS.Models;
using LUSSIS.Models.WebAPI;
using LUSSIS.Repositories;

namespace LUSSIS.Controllers.WebAPI
{
    //Authors: Ton That Minh Nhat
    public class RequisitionsController : ApiController
    {
        private readonly RequisitionRepository _requistionRepo = new RequisitionRepository();
        private readonly DisbursementRepository _disbursementRepo = new DisbursementRepository();
        private readonly DelegateRepository _delegateRepo = new DelegateRepository();
        private readonly EmployeeRepository _employeeRepo = new EmployeeRepository();
        private readonly StationeryRepository _stationeryRepo = new StationeryRepository();

        //GET: api/Requisitions/
        [Route("api/Requisitions/Pending/{dept}")]
        public IEnumerable<RequisitionDTO> GetPending(string dept)
        {
            var list = _requistionRepo.GetPendingListForHead(dept).ToList();

            var result = list.Select(item => new RequisitionDTO()
            {
                RequisitionId = item.RequisitionId,
                RequisitionEmp = new EmployeeDTO(item.RequisitionEmployee),
                RequisitionDate = item.RequisitionDate,
                ApprovalEmp = null,
                ApprovalRemarks = item.ApprovalRemarks ?? "",
                RequestRemarks = item.RequestRemarks ?? "",
                RequisitionDetails = item.RequisitionDetails.Select(detail => new RequisitionDetailDTO()
                {
                    ItemNum = detail.ItemNum,
                    Description = detail.Stationery.Description,
                    UnitOfMeasure = detail.Stationery.UnitOfMeasure,
                    Quantity = detail.Quantity
                })
            });

            return result;
        }

        [HttpGet]
        [Route("api/Requisitions/Process")]
        public IHttpActionResult Test(int empnum, string status)
        {
            return Ok(empnum + status);
        }

        [HttpPost]
        [Route("api/Requisitions/Process")]
        public async Task<IHttpActionResult> Process([FromBody] RequisitionDTO requisition)
        {
            if (requisition.RequisitionEmpNum == requisition.ApprovalEmpNum)
            {
                return BadRequest("Employee cannot process its own requisition");
            }

            var employee = _employeeRepo.GetById(requisition.ApprovalEmpNum);
            if (_delegateRepo.FindCurrentByDeptCode(employee.DeptCode) != null)
            {
                return BadRequest("Must revoke current delegate to approve.");
            }

            try
            {
                var req = await _requistionRepo.GetByIdAsync(requisition.RequisitionId);
                req.ApprovalEmpNum = requisition.ApprovalEmpNum;
                req.ApprovalRemarks = requisition.ApprovalRemarks;
                req.ApprovalDate = DateTime.Today;
                req.Status = requisition.Status;

                await _requistionRepo.UpdateAsync(req);

                //Send email
                var toEmail = _employeeRepo.GetById(requisition.RequisitionEmpNum).EmailAddress;
                var approvalEmail = _employeeRepo.GetById(requisition.ApprovalEmpNum).EmailAddress;
                var email = new LUSSISEmail.Builder().From(approvalEmail).To(toEmail)
                    .ForRequisitionApproval(req).Build();
                new Thread(delegate() { EmailHelper.SendEmail(email); }).Start();

                return Ok(new {Message = "Updated"});
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        [HttpGet]
        [Route("api/Requisitions/MyReq/{empnum}")]
        public IHttpActionResult MyRequisitions(int empnum)
        {
            var req = _requistionRepo.GetRequisitionsByEmpNum(empnum);
            var result = req.Select(item => new RequisitionDTO()
            {
                ApprovalEmp = item.ApprovalEmployee != null ? new EmployeeDTO(item.ApprovalEmployee) : null,
                ApprovalRemarks = item.ApprovalRemarks,
                RequestRemarks = item.RequestRemarks,
                RequisitionDate = item.RequisitionDate,
                RequisitionEmp = new EmployeeDTO(item.RequisitionEmployee),
                RequisitionId = item.RequisitionId,
                Status = item.Status,
                RequisitionDetails = item.RequisitionDetails.Select(detail => new RequisitionDetailDTO()
                {
                    ItemNum = detail.Stationery.ItemNum,
                    Description = detail.Stationery.Description,
                    Quantity = detail.Quantity,
                    UnitOfMeasure = detail.Stationery.UnitOfMeasure
                })
            });

            return Ok(result);
        }

        [HttpGet]
        [Route("api/Requisitions/Retrieval")]
        public IEnumerable<RetrievalItemDTO> GetRetrievalList()
        {
            return _disbursementRepo.GetRetrievalInProcess().Select(x => new RetrievalItemDTO
            {
                ItemNum = x.ItemNum,
                CurrentQty = x.CurrentQty,
                BinNum = x.BinNum,
                RequestedQty = x.RequestedQty,
                Description = x.Description,
                UnitOfMeasure = x.UnitOfMeasure
            });
        }

        [HttpPost]
        [Route("api/Requisitions/Create")]
        public IHttpActionResult CreateRequisition([FromBody] RequisitionDTO requisitionDto)
        {
            var empNum = requisitionDto.RequisitionEmpNum;
            var employee = _employeeRepo.GetById(empNum);

            var isDelegated = _delegateRepo.FindCurrentByEmpNum(empNum) != null;
            if (isDelegated) return BadRequest("Delegated staff cannot make request");

            var detail = requisitionDto.RequisitionDetails.First();

            var requisitionDetail = new RequisitionDetail()
            {
                ItemNum = detail.ItemNum,
                Quantity = detail.Quantity,
            };

            var requisition = new Requisition()
            {
                RequisitionEmpNum = requisitionDto.RequisitionEmpNum,
                DeptCode = employee.DeptCode,
                RequestRemarks = requisitionDto.RequestRemarks,
                RequisitionDate = DateTime.Today,
                Status = RequisitionStatus.Pending,
                RequisitionDetails = new List<RequisitionDetail>() {requisitionDetail}
            };
            _requistionRepo.Add(requisition);

            requisition.RequisitionDetails.First().Stationery = _stationeryRepo.GetById(detail.ItemNum);
            //Send email on new thread
            var headEmail = _employeeRepo.GetDepartmentHead(employee.DeptCode).EmailAddress;
            var email = new LUSSISEmail.Builder().From(employee.EmailAddress).To(headEmail)
                .ForNewRequistion(employee.FullName, requisition).Build();
            new Thread(delegate() { EmailHelper.SendEmail(email); }).Start();

            return Ok(new {Message = "Requisition created"});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _requistionRepo.Dispose();
                _disbursementRepo.Dispose();
                _delegateRepo.Dispose();
                _employeeRepo.Dispose();
                _stationeryRepo.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

LUSSIS/Views/Requisition/Consolidated.cshtml
@using System.Web.UI.WebControls
@using LUSSIS.Models.WebDTO
@model RetrievalItemsWithDateDTO


@{
    ViewBag.Title = "Consolidated";
}
<h2>Consolidated Stationery Requisitions</h2>
@if (Model.retrievalItems == null || !Model.retrievalItems.Any())
{
    <div class="alert alert-dismissible alert-info">
        <strong>Interesting...</strong> There is no requisition and remaining items to be viewed.
    </div>
}
else
{
    <hr />
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav mr-auto"></div>
        @using (Html.BeginForm("Retrieve", "Requisition", FormMethod.Post, new { @class = "form-inline my-2 my-lg-0" }))
    {
        @Html.AntiForgeryToken()
        @Html.LabelFor(model => model.collectionDate, "Select a collection date", new { @class = "nav-item nav-link" })
        @Html.EditorFor(model => model.collectionDate, new { @class = "form-control mr-sm-2", id = "collectionDate", @Value = Model.collectionDate.Date})
        @Html.ValidationMessageFor(model => model.collectionDate, "must be later than today", new { @class = "invalid-feedback" })
        <div class="nav-item nav-link"><button type="submit" class="btn btn-success my-2 my-sm-0">Arrange Retrieval and Disbursment</button></div>
    }
    </nav>
    <hr />

    <table id="long-table" class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Bin Num</th>
                <th scope="col">Stationery</th>
                <th scope="col">UOM</th>
                <th scope="col">Requested Qty*</th>
                <th scope="col">Available Qty</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.retrievalItems)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.BinNum)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitOfMeasure)
                    </td>

                    <td>
                        @(item.RequestedQty + item.RemainingQty)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AvailableQty)
                    </td>

                </tr>
            }
        </tbody>

    </table>
    <small id="fileHelp" class="form-text text-muted">*Unfullfilled Qty from previous disbursements has been added to Requested Qty</small>
}



@section scripts{
    <script type="text/javascript">
        $(function () {
            $('#collectionDate').datetimepicker({
                defaultDate: '@Model.collectionDate.Date',
                format: "yyyy-mm-dd",
                minDate: getMoment(),
                maxDate: getMoment().add(1, 'year'),
                showClose: true,
                showClear: true,
                toolbarPlacement: 'top'
            });
         });
        
    </script>
}

LUSSIS/Views/Requisition/PendingRequisition.cshtml
@model IEnumerable<LUSSIS.Models.Requisition>

@{
    ViewBag.Title = "PendingRequisition";
}

<h2>Pending Requisition</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RequisitionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee1.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RequestRemarks)
        </th>
        <th>
            @Html.Display("View")
        </th>
        <th>
            @Html.Display("Manage")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RequisitionDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee1.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RequestRemarks)
        </td>
        <td>
            @Html.ActionLink("Details", "Detail", "Requisition", new { reqId = item.RequisitionId }, null) 
        </td>
        <td>
            @Html.ActionLink("Reject", "Edit", new { id = item.RequisitionId }) |
            @Html.ActionLink("Approve", "Delete", new { id = item.RequisitionId })
        </td>
    </tr>
}

</table>

LUSSIS/Views/Requisition/Retrieve.cshtml
@model IEnumerable<LUSSIS.Models.WebDTO.RetrievalItemDTO>

@{
    ViewBag.Title = "Retrieval In Process";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Retrieval In Process</h2>
@if (Model == null || !Model.Any())
{
    <div class="alert alert-dismissible alert-info">
        <strong>Interesting...</strong> There is no retrieval in process at the moment.
    </div>
}
else
{
    <table id="long-table" class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Bin Num</th>
                <th scope="col">Stationery</th>
                <th scope="col">UOM</th>
                <th scope="col">Requested Qty*</th>
                <th scope="col">Available Qty</th>
                <th scope="col">Adjust</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BinNum)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitOfMeasure)
                    </td>

                    <td>
                        @(item.RequestedQty + item.RemainingQty)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AvailableQty)
                    </td>
                    <td>
                        @Html.ActionLink("Adjust Stock", "CreateAdjustment", "StockAdjustment", new { id = item.ItemNum }, new{ target="_blank", type="button", @class="btn btn-outline-primary" })
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <small id="fileHelp" class="form-text text-muted">*Unfullfilled Qty from previous disbursements has been added to Requested Qty</small>
}