LUSSIS/Controllers/RepAndDelegateController.cs
using LUSSIS.Models.WebDTO;
using LUSSIS.Repositories;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using LUSSIS.Constants;
using LUSSIS.DAL;
using LUSSIS.CustomAuthority;
using LUSSIS.Extensions;
using LUSSIS.Emails;

namespace LUSSIS.Controllers
{
    //Authors: Ong Xin Ying
    [CustomAuthorize(Role.DepartmentHead, Role.Staff)]
    public class RepAndDelegateController : Controller
    {
        private readonly EmployeeRepository _employeeRepo = new EmployeeRepository();
        private readonly DelegateRepository _delegateRepo = new DelegateRepository();
        private readonly RequisitionRepository _requisitionRepo = new RequisitionRepository();
        private readonly DepartmentRepository _departmentRepo = new DepartmentRepository();

        /// <summary>
        /// Return true if a delegate is active as of now.
        /// </summary>
        private bool ExistDelegate
        {
            get
            {
                var deptCode = Request.Cookies["Employee"]?["DeptCode"];
                var current = _delegateRepo.FindExistingByDeptCode(deptCode);
                return current != null;
            }
        }

        //for delegate and head only
        // GET: /RepAndDelegate/
        public ActionResult Index()
        {
            var deptCode = Request.Cookies["Employee"]?["DeptCode"];

            var department = _departmentRepo.GetById(deptCode);
            var existingDelegate = _delegateRepo.FindExistingByDeptCode(deptCode);
            var reqListCount = _requisitionRepo.GetPendingListForHead(deptCode).Count();
            var haveDelegateToday = false;
            if (ExistDelegate)
                haveDelegateToday = existingDelegate.StartDate <= DateTime.Today;

            var dbDto = new DeptHeadDashBoardDTO
            {
                Department = department,
                CurrentDelegate = existingDelegate,
                RequisitionListCount = reqListCount,
                HaveDelegateToday = haveDelegateToday
            };

            return View(dbDto);
        }

        // GET: /RepAndDelegate/DeptRep
        [HeadWithDelegateAuth(Role.DepartmentHead, Role.Staff)]
        public ActionResult DeptRep()
        {
            var deptCode = Request.Cookies["Employee"]?["DeptCode"];
            var department = _departmentRepo.GetById(deptCode);

            var radDto = new RepAndDelegateDTO
            {
                Department = department,
            };

            return View(radDto);
        }

        // GET: /RepAndDelegate/GetEmpJson
        [HttpGet]
        public JsonResult GetEmpJson(string prefix)
        {
            var deptCode = Request.Cookies["Employee"]?["DeptCode"];
            var staffAndRepList = _employeeRepo.GetStaffRepByDeptCode(deptCode);

            if (ExistDelegate)
            {
                var staffDelegate = _employeeRepo.GetById(_delegateRepo.FindExistingByDeptCode(deptCode).EmpNum);
                staffAndRepList.Remove(staffDelegate);
            }

            var selectedList = staffAndRepList
                .Where(e => e.FullName.Contains(prefix, StringComparison.OrdinalIgnoreCase)).ToList();

            var selectedEmps = selectedList.Select(x => new
            {
                x.FullName,
                x.EmpNum
            });

            return Json(selectedEmps, JsonRequestBehavior.AllowGet);
        }

        // GET: /RepAndDelegate/GetEmpForDelJson
        [CustomAuthorize(Role.DepartmentHead)]
        [HttpGet]
        public JsonResult GetEmpForDelJson(string prefix)
        {
            var deptCode = Request.Cookies["Employee"]?["DeptCode"];
            var staffList = _employeeRepo.GetStaffByDeptCode(deptCode);
            var selectedlist = staffList
                .Where(e => e.FullName.Contains(prefix, StringComparison.OrdinalIgnoreCase)).ToList();

            var selectedEmp = selectedlist.Select(x => new
            {
                x.FullName,
                x.EmpNum
            });

            return Json(selectedEmp, JsonRequestBehavior.AllowGet);
        }

        // POST: /RepAndDelegate/UpdateRep
        [HeadWithDelegateAuth(Role.DepartmentHead, Role.Staff)]
        [HttpPost]
        public ActionResult UpdateRep(string repEmp)
        {
            if (ModelState.IsValid)
            {
                var context = new ApplicationDbContext();
                var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

                var deptCode = Request.Cookies["Employee"]?["DeptCode"];
                var department = _departmentRepo.GetById(deptCode);
                var oldRepEmpNum = department.RepEmpNum != null;

                var loginUser = Convert.ToInt32(Request.Cookies["Employee"]?["EmpNum"]);
                var sender = _employeeRepo.GetById(loginUser);

                var newRepEmpNum = Convert.ToInt32(repEmp);
                var newRep = _employeeRepo.GetById(newRepEmpNum);
                var newRepEmailAdd = newRep.EmailAddress;
                newRep.JobTitle = Role.Representative;

                if (!oldRepEmpNum)
                {
                    //update two tables: Employee and Department
                    _employeeRepo.Update(newRep);
                    department.RepEmpNum = newRepEmpNum;
                    _departmentRepo.Update(department);
                    
                    //update aspnetroles
                    var newRepUser = context.Users.FirstOrDefault(u => u.Email == newRep.EmailAddress);
                    userManager.RemoveFromRole(newRepUser?.Id, Role.Staff);
                    userManager.AddToRole(newRepUser?.Id, Role.Representative);
                }
                else
                {
                    //switch roles rep and staff. update both aspnetroles and jobtitles
                    var oldEmpNum = department.RepEmpNum;
                    var oldRep = _employeeRepo.GetById((int)oldEmpNum);
                    var oldRepEmailAdd = oldRep.EmailAddress;
                    oldRep.JobTitle = Role.Staff;

                    var oldRepUser = context.Users.FirstOrDefault(u => u.Email == oldRep.EmailAddress);
                    userManager.RemoveFromRole(oldRepUser?.Id, Role.Representative);
                    userManager.AddToRole(oldRepUser?.Id, Role.Staff);

                    _employeeRepo.Update(newRep);
                    _employeeRepo.Update(oldRep);

                    department.RepEmpNum = newRep.EmpNum;
                    _departmentRepo.Update(department);

                    var newRepUser = context.Users.FirstOrDefault(u => u.Email == newRep.EmailAddress);
                    userManager.RemoveFromRole(newRepUser?.Id, Role.Staff);
                    userManager.AddToRole(newRepUser?.Id, Role.Representative);

                    //email to old rep
                    var emailToOldRep = new LUSSISEmail.Builder().From(sender.EmailAddress)
                    .To(oldRepEmailAdd).ForOldRepresentative().Build();

                    new System.Threading.Thread(delegate () { EmailHelper.SendEmail(emailToOldRep); }).Start();
                }

                //email to new rep
                var emailToNewRep = new LUSSISEmail.Builder().From(sender.EmailAddress)
                    .To(newRepEmailAdd).ForNewRepresentative().Build();

                new System.Threading.Thread(delegate () { EmailHelper.SendEmail(emailToNewRep); }).Start();

            }

            return RedirectToAction("DeptRep");
        }

        // POST: /RepAndDelegate/AddDelegate
        [CustomAuthorize(Role.DepartmentHead)]
        [HttpPost]
        public ActionResult AddDelegate(string delegateEmp, string from, string to)
        {
            if (ModelState.IsValid)
            {
                var empNum = Convert.ToInt32(delegateEmp);
                var newDelegate = _employeeRepo.GetById(empNum);
                var newDelegateEmailAdd = newDelegate.EmailAddress;
                var startDate = DateTime.ParseExact(from, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                var endDate = DateTime.ParseExact(to, "dd/MM/yyyy", CultureInfo.InvariantCulture);

                var loginUser = Convert.ToInt32(Request.Cookies["Employee"]?["EmpNum"]);
                var sender = _employeeRepo.GetById(loginUser);

                var del = new Models.Delegate()
                {
                    EmpNum = empNum,
                    StartDate = startDate,
                    EndDate = endDate
                };

                _delegateRepo.Add(del);

                //email to new delegate
                var emailToNewDelegate = new LUSSISEmail.Builder().From(sender.EmailAddress)
                    .To(newDelegateEmailAdd).ForNewDelegate().Build();
                new System.Threading.Thread(delegate () { EmailHelper.SendEmail(emailToNewDelegate); }).Start();
            }

            return RedirectToAction("MyDelegate");
        }

        // POST: /RepAndDelegate/DeleteDelegate
        [CustomAuthorize(Role.DepartmentHead)]
        [HttpPost]
        public ActionResult DeleteDelegate()
        {
            if (ModelState.IsValid)
            {
                var deptCode = Request.Cookies["Employee"]?["DeptCode"];
                var oldDelegate = _delegateRepo.FindExistingByDeptCode(deptCode);
                var oldDelegateEmailAdd = oldDelegate.Employee.EmailAddress;

                var loginUser = Convert.ToInt32(Request.Cookies["Employee"]?["EmpNum"]);
                var sender = _employeeRepo.GetById(loginUser);

                //email to old delegate
                var emailToOldDelegate = new LUSSISEmail.Builder().From(sender.EmailAddress)
                    .To(oldDelegateEmailAdd).ForOldDelegate().Build();

LUSSIS/Views/RepAndDelegate/DeptRep.cshtml
@model LUSSIS.Models.WebDTO.RepAndDelegateDTO
@{
    ViewBag.Title = "Department Representative";
}
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
<h2>Department Representative</h2>
<hr/>
<div class="jumbotron">
    @if (Model.Department.RepEmployee != null)
    {
        <h5 class="mt-4 mb-5">
            Current Department Representative
        </h5>
        <h2 class="mt-4 mb-5 text-info">
            <strong>
                @Html.DisplayFor(model => model.Department.RepEmployee.FullName)
            </strong>
        </h2>
    }
    else
    {
        <h2 class="mt-4 mb-5 text-info">
            <strong>You have not set any representative at the moment</strong>
        </h2>
    }

    <hr/>
    <h3 class="mt-4 mb-5">Set representative:</h3>

    @using (Html.BeginForm("UpdateRep", "RepAndDelegate", FormMethod.Post))
    {
        <h5>Find Employee:</h5>
        <div class="row m-2">
            <div class="col-lg-10">
                <input id="Emp" type="text" placeholder="Type and Search Name" name="FullName" class="form-control d-inline"/>
                <input type="submit" value="Set New Department Rep" class="btn btn-success form-control d-inline ml-3"/>
                <input type="hidden" id="Emp2" name="RepEmp"/>
            </div>
        </div>
        <h5 id="tagsname" class="text-info m-3"></h5>
        <br/>
    }
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function() {
            $(':input[type="submit"]').prop('disabled', true);
            $('input[type="text"]').keyup(function() {
                if ($(this).val() === '') {
                    $(':input[type="submit"]').prop('disabled', true);
                    $('#tagsname').html('You selected: none ');
                } else {
                    $(':input[type="submit"]').prop('disabled', false);
                }
            });
            $("#Emp").autocomplete({
                source: function(request, response) {
                    $.ajax({
                        url: "@Url.Content("~/")RepAndDelegate/GetEmpJson",
                        type: "GET",
                        dataType: "json",
                        data: { prefix: request.term },
                        success: function(data) {
                            response($.map(data,
                                function(item) {
                                    return { label: item.FullName, value: item.EmpNum };
                                }));
                        }
                    });
                },
                select: function(event, ui) {
                    event.preventDefault();
                    $('#Emp2').val(ui.item.value);
                    $(this).val(ui.item.label);
                    if (ui.item == null) {
                        $("#Emp").val('');
                        $(':input[type="submit"]').prop('disabled', true);
                    } else {
                        $('#tagsname').html('You selected: ' + ui.item.label);
                    }
                },
                change: function(event, ui) {
                    if (ui.item == null) {
                        $("#Emp").val('');
                        $(':input[type="submit"]').prop('disabled', true);
                    } else {
                        $(':input[type="submit"]').prop('disabled', false);
                    }
                },
                focus: function(event, ui) {
                    $(this).val(ui.item.label);
                    if (ui.item == null) {
                        $("#Emp").val('');
                        $(':input[type="submit"]').prop('disabled', true);
                    } else {
                        $(':input[type="submit"]').prop('disabled', false);
                    }
                }
            });;
        })
    </script>
}

@*Authors: Ong Xin Ying*@

LUSSIS/Views/RepAndDelegate/Index.cshtml
@using LUSSIS.Constants
@model LUSSIS.Models.WebDTO.DeptHeadDashBoardDTO
@{
    ViewBag.Title = "My DashBoard";
}

<h2>My DashBoard</h2>
<hr/>
<div class="row">
<div class="col-lg-4 col-md-4 text-center">
    <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 30rem; min-height: 22rem">
        <h4 class="card-header mt-0">Pending Requisitions</h4>
        <div class="card-body">

            @if (Model.RequisitionListCount != 0)
            {
                <table class="table mt-3">
                    <tr>
                        <th>
                            No. of Pending Requisitions
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <h3 class="mt-0 mb-0">
                                @Html.DisplayFor(model => model.RequisitionListCount)
                            </h3>

                        </td>
                    </tr>
                </table>
            }
            else
            {
                <div class="alert alert-dismissible alert-info p-4">
                    <h6>No pending requisitions at the moment.</h6>
                </div>
            }

        </div>
        <div class="card-footer text-center">
            @if (Model.RequisitionListCount != 0)
            {
                using (Html.BeginForm("Pending", "Requisitions", FormMethod.Post))
                {
                    <input type="submit" class="btn btn-success" value="View All" style="width: 100%"/>
                }
            }
        </div>
    </div>
</div>
@if (User.IsInRole(Role.DepartmentHead))
{
    <div class="col-lg-4 col-md-4 text-center">
        <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 30rem; min-height: 22rem">
            <h4 class="card-header mt-0">My @((Model.CurrentDelegate != null && Model.HaveDelegateToday) ? "Current" : null) Delegate</h4>

            @if (Model.CurrentDelegate == null)
            {
                <div class="card-body">
                    <div class="alert alert-dismissible alert-info p-4">
                        <h6>You have no delegate at the moment</h6>
                    </div>
                </div>
                <div class="card-footer text-center">
                    @using (Html.BeginForm("MyDelegate", "RepAndDelegate", FormMethod.Post))
                    {
                        <input type="submit" class="btn btn-success" value="Set My Delegate" style="width: 100%"/>
                    }
                </div>
            }
            else
            {
                <div class="card-body">
                    <table class="table mt-3">
                        <tr>
                            <th>@Html.DisplayFor(model => model.CurrentDelegate.StartDate) - @Html.DisplayFor(model => model.CurrentDelegate.EndDate)</th>
                        </tr>

                        <tr>
                            <td>
                                <h3 class="mt-0 mb-0">@Html.DisplayFor(model => model.CurrentDelegate.Employee.FullName)</h3>
                            </td>

                        </tr>

                    </table>

                    @if (@Model.CurrentDelegate.StartDate > DateTime.Today)
                    {
                        <h6 class="text-muted">Starting in @((int) (Model.CurrentDelegate.StartDate.Subtract(DateTime.Today)).TotalDays) day(s)</h6>
                    }
                    else
                    {
                        if (Model.CurrentDelegate.EndDate == DateTime.Today)
                        {
                            <h6 class="text-muted">Ending Today</h6>
                        }
                        else
                        {
                            <h6 class="text-muted">Ending in @((int) (Model.CurrentDelegate.EndDate.Subtract(DateTime.Today)).TotalDays) day(s)</h6>
                        }
                    }

                </div>
                <div class="card-footer text-center">
                    @using (Html.BeginForm("DeleteDelegate", "RepAndDelegate", FormMethod.Post))
                    {
                        <input type="submit" class="btn btn-success" value="Revoke Delegate" style="width: 100%"/>
                    }
                </div>
            }
        </div>
    </div>
}
else
{
    <div class="col-lg-4 col-md-4">
        <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 30rem; min-height: 22rem">
            <h4 class="card-header mt-0">Your Delegation Period</h4>
            <div class="card-body">

                <table class="table mt-2">
                    <tr>
                        <th>@Html.DisplayFor(model => model.CurrentDelegate.StartDate) - @Html.DisplayFor(model => model.CurrentDelegate.EndDate)</th>
                    </tr>

                    <tr>
                        <td>
                            @if (Model.CurrentDelegate.EndDate == DateTime.Today)
                            {
                                <h3 class="mt-2 mb-0 text-muted">Ending Today</h3>
                            }
                            else
                            {
                                <h3 class="mt-2 mb-0 text-muted">Ending in @((int) Model.CurrentDelegate.EndDate.Subtract(DateTime.Today).TotalDays) day(s)</h3>
                            }
                        </td>

                    </tr>

                </table>


            </div>
            <div class="card-footer text-center">
                @using (Html.BeginForm("DeleteDelegate", "RepAndDelegate", FormMethod.Post))
                {
                    <input type="submit" class="btn btn-secondary" value="Revoke Delegate" style="width: 100%" disabled/>
                }
            </div>
        </div>
    </div>
}
<div class="col-lg-4 col-md-4 text-center">
    <div class="card border-dark mb-3 text-center bg-transparent" style="max-width: 30rem; min-height: 22rem">
        <h4 class="card-header mt-0">Department Rep</h4>
        <div class="card-body">
            @if (Model.Department.RepEmployee != null)
            {
                <table class="table mt-3">
                    <tr>
                        <th>
                            Current Department Rep
                        </th>
                    </tr>

                    <tr>
                        <td>
                            <h3 class="mt-0 mb-0">
                                @Html.DisplayFor(model => model.Department.RepEmployee.FullName)
                            </h3>
                        </td>
                    </tr>
                </table>
            }
            else
            {
                <div class="alert alert-dismissible alert-info p-4">
                    <h6>No department representative at the moment.</h6>
                </div>
            }
        </div>

        <div class="card-footer text-center">
            @using (Html.BeginForm("DeptRep", "RepAndDelegate", FormMethod.Post))
            {
                if (User.IsInRole(Role.DepartmentHead) && !Model.HaveDelegateToday
                    || User.IsInRole(Role.Staff) && Model.HaveDelegateToday)
                {
                    if (Model.Department.RepEmployee == null)
                    {
                        <input type="submit" class="btn btn-success" value="Set New Rep" style="width: 100%"/>
                    }
                    else
                    {
                        <input type="submit" class="btn btn-success" value="Change Rep" style="width: 100%"/>
                    }
                }

                else
                {
                    if (Model.Department.RepEmployee == null)
                    {
                        <input type="submit" class="btn btn-secondary" value="Set New Rep" style="width: 100%" disabled/>
                    }
                    else
                    {
                        <input type="submit" class="btn btn-secondary" value="Change Rep" style="width: 100%" disabled/>
                    }
                }
            }

        </div>
    </div>
</div>
</div>

@*Authors: Ong Xin Ying*@

LUSSIS/Views/RepAndDelegate/MyDelegate.cshtml
@model LUSSIS.Models.WebDTO.RepAndDelegateDTO
@{
    ViewBag.Title = "Department Delegate";
}
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
<h2>My Delegate</h2>
<hr/>
<div class="jumbotron">
    @if (Model.MyDelegate != null)
    {
        <h2 class="mt-4 mb-5 text-info">
            <strong>
                @Html.DisplayFor(model => model.MyDelegate.Employee.FullName)
            </strong>
        </h2>
        <h4 class="mb-5">@Html.DisplayFor(model => model.MyDelegate.StartDate) - @Html.DisplayFor(model => model.MyDelegate.EndDate)</h4>
        <h5 class="mt-4 mb-5 text-muted">
            @(Model.MyDelegate.StartDate > DateTime.Today ?
                  "Starting in " + (int) Model.MyDelegate.StartDate.Subtract(DateTime.Today).TotalDays + " day(s)" :
                  (Model.MyDelegate.EndDate == DateTime.Today ? "Ending Today" :
                      "Ending in " + (int) Model.MyDelegate.EndDate.Subtract(DateTime.Today).TotalDays + " day(s)"))
        </h5>
        using (Html.BeginForm("DeleteDelegate", "RepAndDelegate", FormMethod.Post))
        {
            <input type="submit" class="btn btn-success btn-lg" value="Revoke Delegate"/>
        }
        <br/>
    }
    else
    {
        <h2 class="mt-4 mb-5 text-info">
            <strong>You have not set any delegate at the moment</strong>
        </h2>

        <hr/>
        <h3 class="mt-4 mb-5">Set delegate:</h3>

        using (Html.BeginForm("AddDelegate", "RepAndDelegate", FormMethod.Post))
        {
            <h5>Select Date:</h5>
            <div class="row m-2 mb-5">
                <div class="col-lg-6">From &nbsp;<input type="text" id="from" name="from" onkeydown="return false" placeholder="DD/MM/YYYY" class="form-control d-inline"/></div>
                <div class="col-lg-6">To &nbsp;<input type="text" id="to" name="to" onkeydown="return false" placeholder="DD/MM/YYYY" class="form-control d-inline"/></div>
            </div>
            <h5>Find Employee:</h5>
            <div class="row m-2">
                <div class="col-lg-10">
                    <input id="Emp" type="text" placeholder="Type and Search Name" name="FullName" class="form-control d-inline"/>
                    <input id="Submit1" type="submit" value="Set New Delegate" class="btn btn-success form-control d-inline ml-3"/>
                    <input type="hidden" id="Emp2" name="DelegateEmp"/>
                </div>
            </div>
            <h5 id="tagsname" class="text-info m-3"></h5>
            <br/>
        }
    }
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function() {
            $('#Submit1').prop('disabled', true);
            $('#from, #to').change(validate);
            $('#Emp').keyup(validate2);

            //$('#from, #to, #Emp').select(validate);
            function validate() {
                if ($('#from').val().length > 0 &&
                    $('#to').val().length > 0 &&
                    $('#Emp').val().length > 0) {
                    $("#Submit1").prop("disabled", false);
                } else {
                    $("#Submit1").prop("disabled", true);
                }
            };

            function validate2() {
                if ($('#from').val().length > 0 &&
                    $('#to').val().length > 0 &&
                    $('#Emp').val().length > 0) {
                    $("#Submit1").prop("disabled", false);
                } else {
                    $("#Submit1").prop("disabled", true);
                    $('#tagsname').html('You selected: none');
                }
            };

            var dateNow = new Date();
            var dateToday = moment(dateNow).format('DD/MM/YYYY');
            $(function() {
                from = $("#from")
                        .datepicker({
                            dateFormat: 'dd/mm/yy',
                            minDate: dateToday,
                            changeMonth: true,
                            numberOfMonths: 1
                        })
                        .on("change",
                            function() {
                                to.datepicker("option", "minDate", getDate(this));
                            }),
                    to = $("#to").datepicker({
                            dateFormat: 'dd/mm/yy',
                            changeMonth: true,
                            numberOfMonths: 1
                        })
                        .on("change",
                            function() {
                                from.datepicker("option", "maxDate", getDate(this));
                            });

                function getDate(element) {
                    var date;
                    try {
                        date = $.datepicker.parseDate("dd/mm/yy", element.value);
                    } catch (error) {
                        date = null;
                    }

                    return date;
                }
            });

            $("#Emp").autocomplete({
                source: function(request, response) {
                    $.ajax({
                        url: "@Url.Content("~/")RepAndDelegate/GetEmpForDelJson",
                        type: "GET",
                        dataType: "json",
                        data: { prefix: request.term },
                        success: function(data) {
                            response($.map(data,
                                function(item) {
                                    return { label: item.FullName, value: item.EmpNum };
                                }));
                        }
                    });
                },
                select: function(event, ui) {
                    event.preventDefault(); //default gives the value instead of label.
                    $('#Emp2').val(ui.item.value);
                    $(this).val(ui.item.label);
                    if (ui.item == null) {
                        $("#Emp").val('');
                        $('#tagsname').html('You selected: none');

                    } else {
                        $('#tagsname').html('You selected: ' + ui.item.label);
                    }
                },
                change: function(event, ui) {
                    if (ui.item == null) {
                        $("#Emp").val('');
                        $('#tagsname').html('You selected: none');
                        $('#Submit1').prop('disabled', true);
                    }
                },
                focus: function(event, ui) {
                    $(this).val(ui.item.label);
                    if (ui.item == null) {
                        $("#Emp").val('');
                        $('#tagsname').html('You selected: none');
                        $('#Submit1').prop('disabled', true);
                    }
                },
                close: function(event, ui) {
                    $(this).data().term = null;
                }
            });
        });
    </script>
}

@*Authors: Ong Xin Ying*@