LUSSIS/Controllers/CollectionController.cs
using LUSSIS.Models.WebDTO;
using LUSSIS.Repositories;
using System;
using System.Web.Mvc;
using LUSSIS.Constants;

namespace LUSSIS.Controllers
{
    //Authors: Ong Xin Ying
    [Authorize(Roles = Role.Representative)]
    public class CollectionController : Controller
    {
        private readonly DisbursementRepository _disbursementRepo = new DisbursementRepository();
        private readonly CollectionRepository _collectionRepo = new CollectionRepository();
        private readonly DepartmentRepository _departmentRepo = new DepartmentRepository();

        // GET: /Collection/
        public ActionResult Index()
        {
            var deptCode = Request.Cookies["Employee"]?["DeptCode"];
            var disbursement = _disbursementRepo.GetByDateAndDeptCode(DateTime.Now, deptCode);
            return View(disbursement);
        }

        // GET: /Collection/SetCollection
        public ActionResult SetCollection()
        {
            var manageCollectionDto = new ManageCollectionDTO();
            var deptCode = Request.Cookies["Employee"]?["DeptCode"];
            manageCollectionDto.CollectionPoint = _collectionRepo.GetCollectionPointByDeptCode(deptCode);
            manageCollectionDto.CollectionPoints = _collectionRepo.GetAll();
            return View(manageCollectionDto);
        }

        // POST: /Collection/UpdateCollection
        [HttpPost]
        public ActionResult UpdateCollection(ManageCollectionDTO manageCollectionDto)
        {
            if (ModelState.IsValid)
            {
                var deptCode = Request.Cookies["Employee"]?["DeptCode"];
                var department = _departmentRepo.GetById(deptCode);

                department.CollectionPointId = manageCollectionDto.DeptCollectionPointId;
                _departmentRepo.Update(department);

                ViewData["message"] = "Collection Point updated successfully";
                return PartialView("_SetCollection", department.CollectionPoint);
            }

            return RedirectToAction("SetCollection");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _disbursementRepo.Dispose();
                _collectionRepo.Dispose();
                _departmentRepo.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

LUSSIS/Views/Collection/Index.cshtml
@model LUSSIS.Models.Disbursement

@{
    ViewBag.Title = "Upcoming Collection";
}

<h2>Upcoming Collection</h2>
<hr/>

@if (@Model == null || @Model.DisbursementDetails.Count == 0)
{
    <div class="alert alert-dismissible alert-info">
        <br/>
        <strong>No disbursement to be collected at the moment.</strong> <br/><br/>
    </div>
}
else
{
    <table class="table table-dark">
        <tr class="table-active">
            <th>
                @Html.DisplayNameFor(model => model.CollectionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CollectionPoint.CollectionName)

            </th>
        </tr>
        <tr class="table-dark">
            <td>
                @Html.DisplayFor(model => model.CollectionDate)&nbsp;&nbsp;&nbsp;@Html.DisplayFor(model => model.CollectionPoint.Time)
            </td>
            <td>
                @Html.DisplayFor(model => model.CollectionPoint.CollectionName)
            </td>
        </tr>

    </table>

    <h5>Items to be collected</h5>
    <table class="table table-hover">
        <tr class="table-active">
            <th>
                @Html.DisplayNameFor(model => model.DisbursementDetails.First().Stationery.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DisbursementDetails.First().Stationery.UnitOfMeasure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DisbursementDetails.First().RequestedQty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DisbursementDetails.First().ActualQty)
            </th>
        </tr>

        @foreach (var item in Model.DisbursementDetails)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Stationery.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stationery.UnitOfMeasure)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestedQty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActualQty)
                </td>
            </tr>
        }
    </table>
}

@*Authors: Ong Xin Ying*@

LUSSIS/Views/Collection/SetCollection.cshtml
@model LUSSIS.Models.WebDTO.ManageCollectionDTO

@{
    ViewBag.Title = "Manage Collection Point";
}

<h2>Manage Collection Point</h2>
<hr/>
@using (Ajax.BeginForm("UpdateCollection", "Collection", new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "currentPoint"
}))
{
    @Html.Partial("_SetCollection", Model.CollectionPoint)

    <div class="card border-dark mb-3 bg-transparent ">
        <h5 class="card-header bg-dark" style="margin-top: 0; color: whitesmoke">
            Set New Collection Point
        </h5>
        <div class="card-body">
            <small class="card-subtitle text-muted">New collection point is effective from the next upcoming collection<br/> (current collection will not be affected)</small>
        </div>@*@using (Html.BeginForm("UpdateCollection", "Collection", FormMethod.Post))*@

        <ul class="list-group list-group-flush bg-transparent">
            @foreach (var item in Model.CollectionPoints)
            {
                <label class="btn btn-outline-dark text-left">
                    @Html.RadioButtonFor(model => model.DeptCollectionPointId, item.CollectionPointId,
                        item.CollectionName == Model.CollectionPoint.CollectionName ? new {@checked = "checked", @class = "btn btn-primary"} : null)

                    @item.CollectionName
                    @item.Time
                </label>
            }

            <li class="list-group-item bg-transparent">
                <input type="submit" value="Set New Collection Point" class="btn btn-success" style="padding: 0.5rem 3rem"/>
            </li>

        </ul>

        <div class="embed-responsive embed-responsive-16by9">
            <iframe src="https://snazzymaps.com/embed/41737" width="1200" height="500" style="border: none;"></iframe>
        </div>
    </div>
}


@section scripts {
    <script src="~/Scripts/jquery.unobstrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}


@*Authors: Ong Xin Ying*@

LUSSIS/Views/Collection/_SetCollection.cshtml
@model LUSSIS.Models.CollectionPoint
<div id="currentPoint">
    <div class="card border-dark mb-3 bg-transparent">
        <h5 class="card-header bg-dark" style="margin-top: 0; color:whitesmoke">
            Current Collection Point and Time
        </h5>
        <div class="card-body">
            <h4 class="card-title">@Html.DisplayFor(model => model.CollectionName)</h4>
            <h5 class="card-subtitle text-muted">
                @Html.DisplayFor(model => model.Time)
            </h5>
            &nbsp;<small class="text-danger" id="message">@ViewData["message"]</small>
        </div>
    </div>
</div>
<script>
    $("#message").show();
    setTimeout(function () { $("#message").hide(); }, 1200);
</script>